### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by ski7777** [yaamai/go-nsdp#1]
Hi,

I recently bought a GS308E but I'm unable to understand how to set vlans.
I have NSDP management and 802.1Q advanced enabled.

Can you give me some example commands?

**Comment by yaamai** [comment]
Here are some example commands.

- set vlan-id for untagged-frame (aka Native VLAN)
```
export NSDP_PASSWORD=password
port_id=8
vlan_id=1
nsdp-cli set tag-vlan-pvid:$port_id:$vlan_id
```

- set member ports for tagged-vlan
```
export NSDP_PASSWORD=password
vlan_id=1000
port_id=8
nsdp-cli set tag-vlan:$vlan_id:$port_id:$port_id
```

- set member ports for untagged-vlan
```
export NSDP_PASSWORD=password
vlan_id=1000
port_id=8
nsdp-cli set tag-vlan:$vlan_id:$port_id:
```

- receive port 5 untagged-frame as tagged vlan(1000) frame from port 1 (like port5: access, port1: trunk)
  (In my setup, connect raspberry pi to port 5 and router to port 1.
  Then configure router to receive tagged vlan 1000 to connect raspberry pis)
```
export NSDP_PASSWORD=password
vlan_id=1000
device_port_id=5
router_port_id=1
nsdp-cli set tag-vlan-pvid:$device_port_id:$vlan_id tag-vlan:$vlan_id:$router_port_id,$device_port_id:$router_port_id
```

**Comment by ski7777** [comment]
Thanks for your help. Now I got this massive bummer working:
`nsdp-cli set tag-vlan:1:: tag-vlan:2:1,3,5,6,7,8:8 tag-vlan:3:2,4,8:8 tag-vlan:4:8:8 tag-vlan-pvid:1:2 tag-vlan-pvid:2:3 tag-vlan-pvid:3:2 tag-vlan-pvid:4:3 tag-vlan-pvid:5:2 tag-vlan-pvid:6:2 tag-vlan-pvid:7:2 tag-vlan-pvid:8:2`
